### ISSUE TITLE
Rat reference genome

### ISSUE THREAD

**Issue by dksenthil** [ribosomeprofiling/references_for_riboflow#2]
Hi, I intend to use the Riboflow pipeline for my new riboseq data from Rat. Previously I used Riboviz for my analysis. I am interested in using the new Nextflow pipeline. Can you add the rat genome reference.

**Comment by cancenik** [comment]
Glad to hear your interest in using Riboflow. We currently do not have the reference files for rat. However, you can see instructions on generating your own reference. Sorry for the slow response.
